[postgres]
host = "localhost"
port = 5432
user = "usr"
password = "pwd"
db_name = "db"
ssl_mode = "disable"
migrations_path = "app/migrations"

[minio]
host = "localhost"
port = 9000
user = "minio"
password = "password"
articles_bucket = "articles"
attachments_bucket = "attachments"
avatars_bucket = "avatars"
use_ssl = false
url_lifetime = "24h"

[search]
search_url = "http://localhost:5255/search"

[container]
bot_id = 1
project_id = 1
user_id = 3
name = "Test project bot"
description = "Test project bot"
icon = ""

[telegram]
bot_token = "7672631119:AAEqdcBCTP1FEtS96JrVd1FU-Zc1JC8NLjo"
information_url = ""
hello_message = [
  "*👨‍💻 Привет! Я бот поддержки*",
  "Я могу ответить на все ваши вопросы!",
  "*Напишите мне,* и я постараюсь помочь вам!",
]
error_message = "Если Вы не нашли ответа на свой вопрос или нуждаетесь в консультации наших технических специалистов, оставьте запрос для службы поддержки"
main_image = ""
main_buttons = [{ text = "✏️  Задать вопрос", data = "ask_question" }]
